name: flutter_hooks_test

description: Simple and complete Flutter hooks testing utilities that encourage good testing practices..
version: 0.0.3
homepage: https://github.com/wasabeef/flutter_hooks_test
repository: https://github.com/wasabeef/flutter_hooks_test
documentation: https://github.com/wasabeef/flutter_hooks_test
issue_tracker: https://github.com/wasabeef/flutter_hooks_test/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_hooks: '>=0.18.0'

dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.3.0
  melos: ^3.0.1
